class DocumentationGenerator:
    def _collect_scopes(self, scope, depth=0):
        """Recursively collect scope information for documentation."""
        lines = []
        indent = "  " * depth
        lines.append(f"{indent}### Scope: `{scope.name}`\n")
        if scope.symbols:
            lines.append(f"{indent}| Variable | Type | Value | Constant |\n")
            lines.append(f"{indent}|----------|------|-------|----------|\n")
            for name, sym in scope.symbols.items():
                val = sym.value if sym.value is not None else "undefined"
                const = "Yes" if sym.is_constant else "No"
                lines.append(f"{indent}| `{sym.name}` | `{sym.type}` | `{val}` | {const} |\n")
        else:
            lines.append(f"{indent}_No variables in this scope._\n")
        
        for child in scope.children:
            lines.append("\n")
            lines.extend(self._collect_scopes(child, depth + 1))
        return lines

    def generate(self, ast, symbol_table, optimization_log, source_code, target_code):
        doc = []
        doc.append("# Compilation Report\n")
        doc.append("---\n")
        
        doc.append("## Source Code\n")
        doc.append("```c\n" + source_code + "\n```\n")
        
        doc.append("## Symbol Table & Scope Analysis\n")
        scope_lines = self._collect_scopes(symbol_table)
        doc.extend(scope_lines)
        
        doc.append("\n## AST Summary\n")
        if hasattr(ast, 'statements'):
            doc.append(f"- **Total statements**: {len(ast.statements)}\n")
            for i, stmt in enumerate(ast.statements):
                doc.append(f"- Statement {i+1}: `{stmt.__class__.__name__}`\n")
        
        doc.append("\n## Optimizations Applied\n")
        if optimization_log:
            for opt in optimization_log:
                doc.append(f"- ✅ {opt}\n")
        else:
            doc.append("- _No optimizations applied._\n")
        
        doc.append("\n## Generated Target Code (MIPS)\n")
        doc.append("```asm\n" + target_code + "\n```\n")
        
        doc.append("\n---\n")
        doc.append("_Report auto-generated by the Compiler Visualizer documentation pass._\n")
        
        return "\n".join(doc)